-- V2__detection.sql
-- 탐지 모듈(P3): 차단 IP 목록 + 보안 이벤트 감사 로그.
-- H2(dev)/PostgreSQL(prod) 양쪽에서 동작하는 표준 SQL 사용.

CREATE TABLE blocked_ip (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip            VARCHAR(64)  NOT NULL,
    reason        VARCHAR(255),
    blocked_at    TIMESTAMP    NOT NULL,
    blocked_until TIMESTAMP    NOT NULL
);
CREATE INDEX idx_blocked_ip_ip ON blocked_ip (ip);
CREATE INDEX idx_blocked_ip_until ON blocked_ip (blocked_until);

CREATE TABLE security_event (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(40)  NOT NULL,
    ip         VARCHAR(64),
    detail     VARCHAR(500),
    created_at TIMESTAMP    NOT NULL
);
CREATE INDEX idx_security_event_type_ip ON security_event (type, ip);
CREATE INDEX idx_security_event_created ON security_event (created_at);
