-- V4__users.sql
-- 인증 모듈(P2): 사용자 계정 테이블.
-- H2(dev)/PostgreSQL(prod) 양쪽에서 동작하는 표준 SQL 사용.

CREATE TABLE users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(50)  NOT NULL UNIQUE,
    password_hash      VARCHAR(255) NOT NULL,
    role               VARCHAR(20)  NOT NULL,
    enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_login_count INTEGER      NOT NULL DEFAULT 0,
    locked_until       TIMESTAMP
);
