-- V6__refresh_tokens.sql
-- Refresh 토큰 저장소(회전/폐기용). 토큰 원문이 아니라 SHA-256 해시만 저장한다.
-- H2(dev)/PostgreSQL(prod) 양쪽에서 동작하는 표준 SQL.

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    username   VARCHAR(50) NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    created_at TIMESTAMP   NOT NULL
);
CREATE UNIQUE INDEX idx_refresh_token_hash ON refresh_token (token_hash);
CREATE INDEX idx_refresh_token_username ON refresh_token (username);
